module.exports = {
    POINTS_EARNED: 'POINTS_EARNED',
    POINTS_FAILED: 'POINTS_FAILED',
    POINTS_ALLOCATED: 'POINTS_ALLOCATED',
    ORDER_COMPLETE: 'ORDER_COMPLETE',
    ORDER_FAILED: 'ORDER_FAILED',
    ORDER_ASSET: 'ORDER_ASSET'
}